version: 2
jobs:
  build_examples:
    machine: true
    steps:
      - checkout
      - run:
          name: Build examples
          command: ~/project/buildexamples.sh
  build_spec:
    machine: true
    steps:
      # use the github deploy key
      - add_ssh_keys:
          fingerprints:
            - "33:26:15:d0:f2:e8:4f:d7:26:8b:b1:9b:a2:1c:ca:f2"
      - checkout
      - run:
          name: Generate and validate HTML
          command: |
            if [ $CIRCLE_BRANCH = "master" ]; then
              ~/project/builddoc.sh checkLinks
            else
              ~/project/builddoc.sh
            fi
          no_output_timeout: 60m
      - run:
          name: Create archive
          command: |
            cd ~/project
            zip fmi-standard.zip README.adoc CHANGELOG.adoc LICENSE.txt docs/index.html docs/fmi-spec.css docs/images/* headers/*.h schema/*.xsd
      - store_artifacts:
          path: ~/project/fmi-standard.zip
      - run:
          name: Push HTML to fmi-standard.org
          command: |
            if [ $CIRCLE_BRANCH = "master" ]; then
              cd
              git config --global user.email "circleci@fmi-standard"
              git config --global user.name "Circle CI"
              git clone git@github.com:modelica/fmi-standard.org.git
              rsync -a --delete --exclude *.adoc ~/project/docs/ ~/fmi-standard.org/docs/3.0-dev/
              cd fmi-standard.org
              git add docs/3.0-dev
              git commit -m "Update generated specification from fmi-standard (${CIRCLE_SHA1:0:7})" || echo "No changes to commit"
              git push
            fi

workflows:
  version: 2
  validate_and_build:
    jobs:
      - build_examples
      - build_spec
